runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_9w13rpc8:30keibbjjdp6qf0cktl3pjulk6@ds253094.mlab.com:53094/heroku_9w13rpc8
  APP_ID: <federico-hichapp>
  MASTER_KEY: <CodepathMoveFastParse>
  SERVER_URL: https://federico-hitchapp.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:
